### ISSUE TITLE
最长训练长度 

### ISSUE THREAD

**Issue by icemoon-creative** [Tele-AI/Telechat#14]
<img width="875" alt="image" src="https://github.com/Tele-AI/Telechat/assets/64944645/0908c9bd-6e9b-4f45-a358-04fc4cf827ce">
求问最长训练长度是如何得到的呢？能否给一个参考代码

**Comment by janelu9** [comment]
> <img width="875" alt="image" src="https://github.com/Tele-AI/Telechat/assets/64944645/0908c9bd-6e9b-4f45-a358-04fc4cf827ce">
> 
> 求问最长训练长度是如何得到的呢？能否给一个参考代码
> 
> 

不知道他这个模型咋写的，我用deepspeed最新版ZERO3报不能反向求导，尽管模型已经设置成了训练模式😅

**Comment by LSX-Sneakerprogrammer** [comment]
> > <img alt="image" width="875" src="https://private-user-images.githubusercontent.com/64944645/297079664-0908c9bd-6e9b-4f45-a358-04fc4cf827ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTk1MDYsIm5iZiI6MTcwNjYxOTIwNiwicGF0aCI6Ii82NDk0NDY0NS8yOTcwNzk2NjQtMDkwOGM5YmQtNmU5Yi00ZjQ1LWEzNTgtMDRmYzRjZjgyN2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyNTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMGI5ZDI1YjhhYWQ5ZGViZGZmMDQ5YWVkYmI1Y2Y4MzUxMmY2ZTVmNTNhM2I2MGRmOTVjMzRlZjI2ODU0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jI0Sk9RXgd_GQ2ctvmSdik--Gh6dkagx--qK-r34X-8">
> > 求问最长训练长度是如何得到的呢？能否给一个参考代码
> 
> 不知道他这个模型咋写的，我用deepspeed最新版ZERO3报不能反向求导，但zero2可以😅 `assert sub_module.training, "backward pass is invalid for module in evaluation mode"`

您好，我们已于两周前修复了这个bug，并在新版deepspeed上测试可以运行，您可以再试一下。

**Comment by windyflare** [comment]
> > > <img alt="image" width="875" src="https://private-user-images.githubusercontent.com/64944645/297079664-0908c9bd-6e9b-4f45-a358-04fc4cf827ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTk1MDYsIm5iZiI6MTcwNjYxOTIwNiwicGF0aCI6Ii82NDk0NDY0NS8yOTcwNzk2NjQtMDkwOGM5YmQtNmU5Yi00ZjQ1LWEzNTgtMDRmYzRjZjgyN2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyNTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMGI5ZDI1YjhhYWQ5ZGViZGZmMDQ5YWVkYmI1Y2Y4MzUxMmY2ZTVmNTNhM2I2MGRmOTVjMzRlZjI2ODU0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jI0Sk9RXgd_GQ2ctvmSdik--Gh6dkagx--qK-r34X-8">
> > > 求问最长训练长度是如何得到的呢？能否给一个参考代码
> > 
> > 
> > 不知道他这个模型咋写的，我用deepspeed最新版ZERO3报不能反向求导，但zero2可以😅 `assert sub_module.training, "backward pass is invalid for module in evaluation mode"`
> 
> 您好，我们已于两周前修复了这个bug，并在新版deepspeed上测试可以运行，您可以再试一下。

您好，我用telechat 7B，运行run_telechat_lora.sh，遇到了相同的问题，请问是哪里出错了呢？

zero_stage设为1，return code -9：

[2024-10-14 08:56:23,627] [ERROR] [launch.py:320:sigkill_handler] ['/opt/conda/bin/python', '-u', 'main.py', '--local_rank=1', '--data_path', '../../example_datas/single_turn_example.jsonl', '--model_name_or_path', '../../models/7B', '--with_loss_mask', '--data_output_path', '/tmp/data_files/', '--per_device_train_batch_size', '1', '--max_seq_len', '1024', '--learning_rate', '3e-6', '--weight_decay', '0.0001', '--num_train_epochs', '5', '--gradient_accumulation_steps', '16', '--lr_scheduler_type', 'cosine', '--warmup_proportion', '0.1', '--seed', '1233', '--zero_stage', '1', '--deepspeed', '--lora_dim', '8', '--mark_only_lora_as_trainable', '--lora_module_name', 'self_attention.', '--output_dir', 'telechat-lora-test'] exits with return code = -9

zero_stage设为3，报如下错误：

Using /home/jovyan/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0002994537353515625 seconds
***** Running training *****
Beginning of Epoch 1/5, Total Micro Batches 176
Traceback (most recent call last):
  File "/data/tele-chat/deepspeed-telechat1/sft/main.py", line 412, in <module>
Traceback (most recent call last):
  File "/data/tele-chat/deepspeed-telechat1/sft/main.py", line 412, in <module>
    main()
  File "/data/tele-chat/deepspeed-telechat1/sft/main.py", line 359, in main
    model.backward(loss)
  File "/data/DeepSpeed-0.9.3/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    main()
  File "/data/tele-chat/deepspeed-telechat1/sft/main.py", line 359, in main
        model.backward(loss)ret_val = func(*args, **kwargs)

  File "/data/DeepSpeed-0.9.3/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/engine.py", line 1862, in backward
    ret_val = func(*args, **kwargs)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/engine.py", line 1862, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/data/DeepSpeed-0.9.3/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
        ret_val = func(*args, **kwargs)self.optimizer.backward(loss, retain_graph=retain_graph)

  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/stage3.py", line 1968, in backward
  File "/data/DeepSpeed-0.9.3/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/stage3.py", line 1968, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
      File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
        Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward passVariable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/parameter_offload.py", line 169, in backward
    return user_fn(self, *args)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/parameter_offload.py", line 169, in backward
        ctx.pre_backward_function(ctx.module)ctx.pre_backward_function(ctx.module)

  File "/data/DeepSpeed-0.9.3/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
  File "/data/DeepSpeed-0.9.3/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)    
ret_val = func(*args, **kwargs)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/parameter_offload.py", line 424, in _run_before_backward_function
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/parameter_offload.py", line 424, in _run_before_backward_function
    self.pre_sub_module_backward_function(sub_module)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    self.pre_sub_module_backward_function(sub_module)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)    
return func(*args, **kwargs)
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/parameter_offload.py", line 500, in pre_sub_module_backward_function
  File "/data/DeepSpeed-0.9.3/deepspeed/runtime/zero/parameter_offload.py", line 500, in pre_sub_module_backward_function
        assert sub_module.training, "backward pass is invalid for module in evaluation mode"assert sub_module.training, "backward pass is invalid for module in evaluation mode"

AssertionError: backward pass is invalid for module in evaluation mode
AssertionError: backward pass is invalid for module in evaluation mode
[vGPU Msg(9343:140387912603456:multiprocess_memory_limit.c:445)]: Calling exit handler 9343
[vGPU Msg(9342:140291496351552:multiprocess_memory_limit.c:445)]: Calling exit handler 9342
