### ISSUE TITLE
执行sh run_telechat_lora.sh时报错，RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by wuxiulike** [Tele-AI/Telechat#33]
300it [00:00, 1675487.62it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 715.50it/s]
300it [00:00, 1757389.94it/s]
Convert token ids: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 61.24it/s]
Exception in thread Thread-4 (_handle_results):
Traceback (most recent call last):
  File "/root/anaconda3/envs/telechat/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/telechat/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/telechat/lib/python3.10/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
  File "/root/anaconda3/envs/telechat/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/root/anaconda3/envs/telechat/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/telechat/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/root/anaconda3/envs/telechat/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/root/anaconda3/envs/telechat/lib/python3.10/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata

**Comment by wuxiulike** [comment]
在shell里运行临时增加限制，就可以了：
# ulimit -n 8192  
#sh run_telechat_lora.sh
